### ISSUE TITLE
What is this library's license?

### ISSUE THREAD

**Issue by Luexa** [kordlib/cache#6]
What license is this code under? There is no LICENSE file in the repository, so I'm unsure what to do if I reference the API in my own application. I'm using Kord and need to cache my own data, so I figure I may as well use the same caching interfaces used by Kord itself, but I need to reference the source code of the caching library to figure out how things should be implemented. I assume the license is MIT like the core Kord library, but I would like confirmation. Thanks!

**Comment by HopeBaron** [comment]
You are free to use the implementation it should've been under the MIT license

really sorry for the delay...
